"""
Prompt templates for label text embeddings.

Adapted from the CLIP prompt-engineering notebook:
    https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb

    Radford, A., Kim, J. W., Hallacy, C., Ramesh, A., Goh, G., Agarwal, S.,
    Sastry, G., Askell, A., Mishkin, P., Clark, J., Krueger, G., & Sutskever, I. (2021).
    "Learning Transferable Visual Models From Natural Language Supervision." ICML 2021.
    arXiv:2103.00020 - https://arxiv.org/abs/2103.00020
    Reference implementation: https://github.com/openai/CLIP (MIT License)
"""

'''
for each image, there may be more than 1 label
i.e an image can contain gluten + dairy
so for EACH label, I need to generate the promts...
'''

FOOD_TEMPLATES = [
    "Identify food items containing {}.",
    "Detect {} in the dish.",
    "Highlight items with {} in the dish.",
    "Find foods that may trigger {} allergies.",
    "Locate {}-containing ingredients in the image.",
    "Check for {} foods in the picture.",
    "Highlight items with {} content.",
    "Identify foods that may pose {} risks.",
    "Find items containing {} allergens.",
    "Detect potential {} in the image.",
    "Analyze the image for {} content.",
    "Spot {} in the picture of the dish.",
    "Highlight potential {} in the food image.",
    "Detect the presence of {} in the food photo.",
    "Identify {}-related elements in the image.",
    "Detect allergens like {} in the food.",
    "Spot {} ingredients in the image.",
    "Highlight potential {} risks in the food photo.",
    "Identify {}-containing foods.",
    "Detect {} presence in the food image.",
    "Spot {} in the picture of the dish.",
    "Highlight {} in the food photo.",
    "Find potential {} in the image.",
    "Identify {} elements in the food picture.",
    "Detect {} in the food image analysis.",
    "Spot {} in the image of the meal.",
    "Highlight potential {} risks in the image.",
    "Identify {}-containing elements in the picture.",
    "Detect the presence of {} in the meal.",
    "Spot {} in the image of the dish.",
    "Highlight {} elements in the picture.",
    "Find potential {} risks in the food image.",
    "Identify {}-containing components in the meal.",
    "Detect {} presence in the dish.",
    "Spot {} in the picture of the cuisine.",
    "Highlight potential {} in the food image.",
    "Identify {}-related components in the dish.",
    "Detect {} in the food photo analysis.",
    "Spot {} in the photo of the meal.",
    "Highlight potential {} risks in the image of the cuisine.",
]

FOOD_NEW_TEMPLATES = [
    "Identify food items containing {}, in particular whether it contains {}.",
    "Highlight dishes that include {}, especially those with {}.",
    "Check for food items that have {}, focusing on {}.",
    "Identify meals containing {}, with an emphasis on {}.",
    "Spot foods that include {}, particularly if they contain {}.",
    "Find dishes with {}, especially if they have {}.",
    "Locate foods containing {}, especially those with {}.",
    "Search for meals that have {}, focusing on {}.",
    "Identify foods with {}, particularly those that contain {}.",
    "Highlight items that include {}, focusing on {}.",
    "Check for meals containing {}, especially those with {}.",
    "Identify dishes with {}, particularly if they have {}.",
    "Spot items that have {}, with a focus on {}.",
    "Find food items with {}, especially if they include {}.",
    "Locate meals that contain {}, with an emphasis on {}.",
    "Search for foods that have {}, focusing on {}.",
    "Identify dishes containing {}, especially if they have {}.",
    "Highlight foods that include {}, particularly those with {}.",
    "Check for items containing {}, focusing on {}.",
    "Identify meals that have {}, particularly those that contain {}.",
    "Locate {}-containing ingredients in the image, where it contains {}.",
    "Find {}-containing elements in the picture, especially if it includes {}.",
    "Spot {}-containing items in the image, particularly those with {}.",
    "Search for {}-containing foods in the picture, especially if they contain {}.",
    "Identify {}-containing ingredients in the image, where it includes {}.",
    "Locate {}-containing foods in the picture, especially those with {}.",
    "Find {}-containing elements in the image, particularly those that have {}.",
    "Spot {}-containing items in the picture, especially if it has {}.",
    "Search for {}-containing ingredients in the image, where they include {}.",
    "Identify {}-containing foods in the picture, particularly those with {}.",
    "Locate {}-containing elements in the image, especially those that contain {}.",
    "Find {}-containing items in the picture, where it has {}.",
    "Spot {}-containing ingredients in the image, particularly those that include {}.",
    "Search for {}-containing foods in the image, where they contain {}.",
    "Identify {}-containing elements in the picture, especially those that have {}.",
    "Locate {}-containing items in the image, where they include {}.",
    "Find {}-containing ingredients in the picture, particularly those with {}.",
    "Spot {}-containing foods in the image, especially if they contain {}.",
    "Search for {}-containing elements in the picture, where it has {}.",
    "Identify {}-containing items in the image, particularly those that have {}.",
    "Check for {}-containing foods in the image, focusing on {}.",
    "Highlight {}-containing ingredients in the picture, where they include {}.",
    "Spot {}-containing items in the image, with an emphasis on {}.",
    "Search for {}-containing elements in the picture, particularly if they contain {}.",
    "Identify {}-containing foods in the image, especially if they have {}.",
    "Locate {}-containing ingredients in the picture, focusing on {}.",
    "Find {}-containing items in the image, where they include {}.",
    "Spot {}-containing elements in the picture, with an emphasis on {}.",
    "Search for {}-containing foods in the image, particularly if they have {}.",
    "Identify {}-containing ingredients in the picture, where they contain {}.",
    "Locate {}-containing foods in the image, especially if they include {}.",
    "Find {}-containing elements in the picture, focusing on {}.",
    "Spot {}-containing ingredients in the image, where they have {}.",
    "Search for {}-containing items in the picture, particularly if they contain {}.",
    "Identify {}-containing elements in the image, especially if they include {}.",
    "Locate {}-containing items in the picture, focusing on {}.",
    "Find {}-containing foods in the image, where they have {}.",
    "Spot {}-containing elements in the picture, with an emphasis on {}.",
    "Search for {}-containing ingredients in the image, particularly if they include {}.",
    "Identify {}-containing items in the picture, especially if they contain {}.",
    "Locate {}-containing elements in the image, focusing on {}.",
    "Find {}-containing ingredients in the picture, where they have {}.",
    "Spot {}-containing foods in the image, particularly if they include {}.",
    "Search for {}-containing items in the picture, with an emphasis on {}.",
    "Identify {}-containing elements in the image, particularly if they contain {}.",
    "Locate {}-containing foods in the picture, where they include {}.",
    "Find {}-containing ingredients in the image, focusing on {}.",
    "Spot {}-containing elements in the picture, where they have {}.",
    "Search for {}-containing items in the image, particularly if they include {}.",
    "Identify {}-containing foods in the picture, especially if they contain {}.",
    "Locate {}-containing ingredients in the image, focusing on {}.",
    "Find {}-containing elements in the picture, where they have {}.",
    "Spot {}-containing foods in the image, with an emphasis on {}.",
    "Search for {}-containing ingredients in the picture, particularly if they contain {}.",
    "Identify {}-containing items in the image, where they include {}.",
    "Locate {}-containing elements in the picture, especially if they have {}.",
    "Find {}-containing foods in the image, focusing on {}.",
    "Spot {}-containing ingredients in the picture, where they contain {}.",
    "Search for {}-containing items in the image, particularly if they have {}.",
    "Identify {}-containing elements in the picture, focusing on {}.",
]

IMAGENET_TEMPLATES = [
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of a {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of a {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of a {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of a {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of a {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of a {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of a {}.",
    "a close-up photo of the {}.",
    "a photo of a {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of a {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of a {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of a {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of a {}.",
    "a cartoon {}.",
    "art of a {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
    "a jpeg corrupted photo of the {}.",
    "a good photo of a {}.",
    "a plushie {}.",
    "a photo of the nice {}.",
    "a photo of the small {}.",
    "a photo of the weird {}.",
    "the cartoon {}.",
    "art of the {}.",
    "a drawing of the {}.",
    "a photo of the large {}.",
    "a black and white photo of a {}.",
    "the plushie {}.",
    "a dark photo of a {}.",
    "itap of a {}.",
    "graffiti of the {}.",
    "a toy {}.",
    "itap of my {}.",
    "a photo of a cool {}.",
    "a photo of a small {}.",
    "a tattoo of the {}."
]

IMAGENET_TEMPLATES_REFINED = [
    "a bad photo of {article} {}.",
    "a photo of many {}.",
    "a sculpture of {article} {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of {article} {}.",
    "graffiti of {article} {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of {article} {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of {article} {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of {article} {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of {article} {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of {article} {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of {article} {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of {article} {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of {article} {}.",
    "a close-up photo of the {}.",
    "a photo of {article} {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of {article} {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of {article} {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of {article} {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of {article} {}.",
    "a cartoon {}.",
    "art of {article} {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of {article} {}.",
    "itap of the {}.",
    "a jpeg corrupted photo of the {}.",
    "a good photo of {article} {}.",
    "a plushie {}.",
    "a photo of the nice {}.",
    "a photo of the small {}.",
    "a photo of the weird {}.",
    "the cartoon {}.",
    "art of the {}.",
    "a drawing of the {}.",
    "a photo of the large {}.",
    "a black and white photo of {article} {}.",
    "the plushie {}.",
    "a dark photo of {article} {}.",
    "itap of {article} {}.",
    "graffiti of the {}.",
    "a toy {}.",
    "itap of my {}.",
    "a photo of a cool {}.",
    "a photo of a small {}.",
    "a tattoo of the {}.",
]

IMAGENET_TEMPLATES_SELECT = [
    "itap of a {}.",
    "a bad photo of the {}.",
    "a origami {}.",
    "a photo of the large {}.",
    "a {} in a video game.",
    "art of the {}.",
    "a photo of the small {}.",
]

extra_templates = [
    'There is {article} {} in the scene.',
    'There is the {} in the scene.',
    'a photo of {article} {} in the scene.',
    'a photo of the {} in the scene.',
    'a photo of one {} in the scene.',


    'itap of {article} {}.',
    'itap of my {}.',  # itap: I took a picture of
    'itap of the {}.',
    'a photo of {article} {}.',
    'a photo of my {}.',
    'a photo of the {}.',
    'a photo of one {}.',
    'a photo of many {}.',

    'a good photo of {article} {}.',
    'a good photo of the {}.',
    'a bad photo of {article} {}.',
    'a bad photo of the {}.',
    'a photo of a nice {}.',
    'a photo of the nice {}.',
    'a photo of a cool {}.',
    'a photo of the cool {}.',
    'a photo of a weird {}.',
    'a photo of the weird {}.',

    'a photo of a small {}.',
    'a photo of the small {}.',
    'a photo of a large {}.',
    'a photo of the large {}.',

    'a photo of a clean {}.',
    'a photo of the clean {}.',
    'a photo of a dirty {}.',
    'a photo of the dirty {}.',

    'a bright photo of {article} {}.',
    'a bright photo of the {}.',
    'a dark photo of {article} {}.',
    'a dark photo of the {}.',

    'a photo of a hard to see {}.',
    'a photo of the hard to see {}.',
    'a low resolution photo of {article} {}.',
    'a low resolution photo of the {}.',
    'a cropped photo of {article} {}.',
    'a cropped photo of the {}.',
    'a close-up photo of {article} {}.',
    'a close-up photo of the {}.',
    'a jpeg corrupted photo of {article} {}.',
    'a jpeg corrupted photo of the {}.',
    'a blurry photo of {article} {}.',
    'a blurry photo of the {}.',
    'a pixelated photo of {article} {}.',
    'a pixelated photo of the {}.',

    'a black and white photo of the {}.',
    'a black and white photo of {article} {}.',

    'a plastic {}.',
    'the plastic {}.',

    'a toy {}.',
    'the toy {}.',
    'a plushie {}.',
    'the plushie {}.',
    'a cartoon {}.',
    'the cartoon {}.',

    'an embroidered {}.',
    'the embroidered {}.',

    'a painting of the {}.',
    'a painting of a {}.',
]